### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by daimoniuma** [aviraxp/AdBlocker_Reborn#29]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
01-21 14:14:02.362 E/Xposed  (26116): 	at com.aviraxp.adblocker.continued.hook.i.鍚煎晩(URLHook.java:18)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.aviraxp.adblocker.continued.hook.i.楦(URLHook.java:62)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.aviraxp.adblocker.continued.hook.i.鍚煎晩(URLHook.java:15)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.aviraxp.adblocker.continued.hook.i$1.beforeHookedMethod(URLHook.java:82)
01-21 14:14:02.362 E/Xposed  (26116): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
01-21 14:14:02.362 E/Xposed  (26116): 	at java.net.URL.<init>(<Xposed>)
01-21 14:14:02.362 E/Xposed  (26116): 	at java.net.URL.<init>(URL.java:435)
01-21 14:14:02.362 E/Xposed  (26116): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
01-21 14:14:02.362 E/Xposed  (26116): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
01-21 14:14:02.362 E/Xposed  (26116): 	at java.net.URL.<init>(<Xposed>)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.mplus.lib.awk.a(SourceFile:84)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.mplus.lib.avj.a(SourceFile:32070)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.mplus.lib.avj.a(SourceFile:16429)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.mplus.lib.avl.a(SourceFile:44)
01-21 14:14:02.362 E/Xposed  (26116): 	at com.mplus.lib.bqe.onHandleIntent(SourceFile:112)
01-21 14:14:02.362 E/Xposed  (26116): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
01-21 14:14:02.362 E/Xposed  (26116): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-21 14:14:02.362 E/Xposed  (26116): 	at android.os.Looper.loop(Looper.java:154)
01-21 14:14:02.362 E/Xposed  (26116): 	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by aviraxp** [comment]
Should be fixed now.
